config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  resources :snippets
  root to: "snippets#new"
  
  mount Sidekiq::Web, at: '/sidekiq'
end

app/models/snippet.rb
class Snippet < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/snippets_controller.rb
class SnippetsController < ApplicationController
  def show
    @snippet = Snippet.find(params[:id])
  end

  def new
    @snippet = Snippet.new
  end

  def create
    @snippet = Snippet.new(snippet_params)
    if @snippet.save
      PygmentsWorker.perform_async(@snippet.id)
      redirect_to @snippet
    else
      render :new
    end
  end



  private

  def snippet_params
    params.require(:snippet).permit(:language, :plain_code)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/snippets_helper.rb
module SnippetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Snippets</title>
    <%= stylesheet_link_tag    "application", media: "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tag %>
  </head>
  <body>
    <div id="container">
      <% flash.each do |name, msg| %>
        <%= content_tag :div, msg, id: "flash_#{name}" %>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/snippets/new.html.erb
<h1>New Snippet</h1>

<%= form_for @snippet do |f| %>
  <% if @snippet.errors.any? %>
    <div class="error_messages">
      <h2><%= pluralize(@snippet.errors.count, "error") %> prohibited this snippet from being saved:</h2>
      <ul>
      <% @snippet.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :language %><br />
    <%= f.select :language, options_for_select([["Ruby", "ruby"], ["Python", "python"], ["JavaScript", "javascript"], ["CSS", "css"]]) %>
  </div>
  <div class="field">
    <%= f.label :plain_code, "Source Code" %><br />
    <%= f.text_area :plain_code, rows: 14, cols: 50 %>
  </div>
  <div class="actions"><%= f.submit "Post Snippet" %></div>
<% end %>

app/views/snippets/show.html.erb
<h1>Snippet</h1>

<p>
  <strong>Language:</strong>
  <%= @snippet.language %>
</p>
<div class="code_block">
  <% if @snippet.highlighted_code.present? %>
    <%= raw @snippet.highlighted_code %>
  <% else %>
    <pre><%= @snippet.plain_code %></pre>
  <% end %>
</div>

<p>
  <%= link_to "New Snippet", new_snippet_path %>
</p>